"""
Scrapes Korean move/ability descriptions from PokeAPI CSV data.
Outputs: play.pokemonshowdown.com/js/ko-desc.js

Korean = language_id 3 in PokeAPI
"""

import urllib.request
import csv
import io
import json
import re

URLS = {
    'move_names':          'https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/move_names.csv',
    'move_flavor':         'https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/move_flavor_text.csv',
    'ability_names':       'https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/ability_names.csv',
    'ability_flavor':      'https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/ability_flavor_text.csv',
}

KOREAN_LANG = '3'

def fetch_csv(url):
    print(f"  Fetching {url.split('/')[-1]} ...")
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req) as r:
        return r.read().decode('utf-8')

def to_showdown_id(name):
    return re.sub(r'[^a-z0-9]', '', name.lower())

def clean_flavor(text):
    """Remove soft hyphens and normalize whitespace from PokeAPI flavor text."""
    text = text.replace('\xad', '')   # soft hyphen
    text = text.replace('\n', ' ')
    text = re.sub(r'  +', ' ', text)
    return text.strip()

def build_name_map(csv_text, id_col):
    """Returns {internal_id: showdown_id} from English names."""
    reader = csv.DictReader(io.StringIO(csv_text))
    mapping = {}
    for row in reader:
        if row['local_language_id'] == '9':  # English
            sid = to_showdown_id(row['name'])
            if sid:
                mapping[row[id_col]] = sid
    return mapping

def build_latest_ko_desc(csv_text, id_col):
    """Returns {internal_id: latest_korean_flavor_text}."""
    reader = csv.DictReader(io.StringIO(csv_text))
    # keep highest version_group_id per move (= most recent game)
    latest = {}
    for row in reader:
        if row['language_id'] != KOREAN_LANG:
            continue
        iid = row[id_col]
        vg = int(row['version_group_id'])
        if iid not in latest or vg > latest[iid][0]:
            latest[iid] = (vg, clean_flavor(row['flavor_text']))
    return {iid: text for iid, (_, text) in latest.items()}

def main():
    print("=== Fetching move data ===")
    move_names_csv   = fetch_csv(URLS['move_names'])
    move_flavor_csv  = fetch_csv(URLS['move_flavor'])

    print("=== Fetching ability data ===")
    abil_names_csv   = fetch_csv(URLS['ability_names'])
    abil_flavor_csv  = fetch_csv(URLS['ability_flavor'])

    print("=== Building mappings ===")
    move_id_map   = build_name_map(move_names_csv,  'move_id')
    move_ko_desc  = build_latest_ko_desc(move_flavor_csv, 'move_id')
    abil_id_map   = build_name_map(abil_names_csv,  'ability_id')
    abil_ko_desc  = build_latest_ko_desc(abil_flavor_csv, 'ability_id')

    # Combine: showdown_id -> korean description
    ko_move_descs = {}
    for iid, sid in move_id_map.items():
        if iid in move_ko_desc:
            ko_move_descs[sid] = move_ko_desc[iid]

    ko_abil_descs = {}
    for iid, sid in abil_id_map.items():
        if iid in abil_ko_desc:
            ko_abil_descs[sid] = abil_ko_desc[iid]

    print(f"  Moves with Korean desc: {len(ko_move_descs)}")
    print(f"  Abilities with Korean desc: {len(ko_abil_descs)}")

    # ------------------------------------------------------------------ output
    out_path = 'play.pokemonshowdown.com/js/ko-desc.js'
    js = f"""// Auto-generated by scripts/scrape_descriptions.py
// Korean move/ability descriptions from PokeAPI (language_id=3, latest version group)
(function () {{
    var koMoveDescs = {json.dumps(ko_move_descs, ensure_ascii=False, indent=4)};

    var koAbilityDescs = {json.dumps(ko_abil_descs, ensure_ascii=False, indent=4)};

    function applyDescs() {{
        if (window.BattleMovedex) {{
            for (var id in koMoveDescs) {{
                if (window.BattleMovedex[id]) {{
                    window.BattleMovedex[id].shortDesc = koMoveDescs[id];
                    window.BattleMovedex[id].desc = koMoveDescs[id];
                }}
            }}
        }}
        if (window.BattleAbilities) {{
            for (var id in koAbilityDescs) {{
                if (window.BattleAbilities[id]) {{
                    window.BattleAbilities[id].shortDesc = koAbilityDescs[id];
                    window.BattleAbilities[id].desc = koAbilityDescs[id];
                }}
            }}
        }}
    }}

    // Run immediately if data is already loaded, and again on window load
    // (CDN scripts may load asynchronously after this script)
    applyDescs();
    window.addEventListener('load', applyDescs);
    // Extra pass after app init in case CDN data loads late
    setTimeout(applyDescs, 3000);
}})();
"""
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(js)
    print(f"=== Written to {out_path} ===")

if __name__ == '__main__':
    main()
